### PR TITLE
LightHouse performance improvements

### PR DESCRIPTION
**Pull request by svenvanhal**
Performance improved based on the LightHouse analysis performed in WISVCH/website#18.

- [x] Use image thumbnails where appropriate.
- [x] Setup image optimization workflow.
- [x] Reduce amount of scripts loaded, move others to footer when possible.
- [x] Improve loading responsive navigation (prevent flickering).
- [ ] ~~Implement some kind of lazy image loading technique.~~
- [x] Improve accessibility.

Fixes WISVCH/website#18.

### CODE REVIEW

**Comment by svenvanhal** [comment]
@TimvdLippe do you think we could do without lazy loading? The frontpage is now below 1MB in total, and the impact would be marginal on image-heavy pages like job openings:

[Front page](https://ch.tudelft.nl): 620kb of images, ~450kb below the fold (of which ~130kb already lazy loaded, so effectively ~320kb)
[Job Openings](https://ch.tudelft.nl/career/job-openings/): 200kb of images, ~110kb below the fold

**Comment by TimvdLippe** [comment]
Per Slack discussion, let's hold off lazy loading images for now. The other
improvements are more important anyways :)

Op di 28 nov. 2017 om 18:05 schreef Sven van Hal <notifications@github.com>:

**Comment by TimvdLippe** [comment]
While this definitely addresses most of the points in https://github.com/WISVCH/website/issues/18, I think the issue should not be closed yet, as we found some more improvements: caching and minification of HTML.

**Comment by svenvanhal** [comment]
We'll use a WordPress plug-in for caching and minification, so this PR can be merged.

**Pull request merged**
